#+AUTHOR: Rohit Goswami
#+email: rgoswami@ieee.org
#+options: tags:nil title:nil toc:nil num:nil author:nil date:nil
# Usage: export to LaTeX, compile with xelatex
* Configuration :ignoreheading:ignore:
:PROPERTIES:
:VISIBILITY: folded
:END:
#+BEGIN_SRC emacs-lisp :exports none :eval always :results none
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
#+END_SRC

** Theme :ignoreheading:ignore:
#+BEGIN_SRC emacs-lisp :exports none :results none :eval always
(setq org-latex-packages-alist 'nil)
(setq org-latex-with-hyperref 'nil)
(setq org-latex-hyperref-template 'nil)
(setq org-latex-minted-options 'nil)
(setq org-latex-listings 'listings)
(add-to-list 'org-latex-classes
  '("rgcv-twopage"
    "\\documentclass[twopage]{rgcv}"
    ("\\section{%s}" . "\\section*{%s}")
    ("\\subsection{%s}" . "\\subsection*{%s}")))
#+END_SRC

*** TeX activation :ignoreheading:ignore:
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: rgcv-twopage

* About :ignoreheading:ignore:noexport:
Two-page CV targeting the SURF HPC Advisor position.
Uses the unified ~rgcv~ class in twopage mode.

* Preamble :ignoreheading:ignore:noexport:
** Bibliography
#+name: twopage_biblio
#+begin_src latex
\usepackage[%
 minbibnames=8,%
 maxbibnames=99,%
 block=space,%
 bibencoding=utf8,%
 backend=biber,%
 url=false,%
 isbn=false,%
 style=publist,%
 fixyear=true,%
 hlyear=true,%
 plauthorname=Goswami,%
 plauthorfirstname=Rohit,%
 plauthorhandling=highlight,%
 plnumbering=local-descending,%
]{biblatex}
\bibliography{publications}

\renewcommand*{\mkbibnamegiven}[1]{%
 \ifitemannotation{highlight}{\textbf{#1}}{#1}}
\renewcommand*{\mkbibnamefamily}[1]{%
 \ifitemannotation{highlight}{\textbf{#1}}{#1}}

\defbibenvironment{midbib}
{\list
 {}
 {
  \setlength{\leftmargin}{0mm}
  \setlength{\itemindent}{-\leftmargin}
  \setlength{\itemsep}{\bibitemsep}
  \setlength{\parsep}{\bibparsep}}
}
{\endlist}
{\item}
#+end_src

** Extra packages
#+name: twopage_extra
#+begin_src latex
\usepackage{xspace}
\usepackage[british]{babel}
\usepackage[autostyle=true]{csquotes}
\usepackage{enumitem}
\setlist[itemize]{nosep, leftmargin=1.5em}
#+end_src

** Tangle
#+begin_src latex :results none :tangle twopage-preamble.tex :noweb yes
<<twopage_biblio>>
<<twopage_extra>>
#+end_src

#+LATEX_HEADER: \input{twopage-preamble.tex}

* Document :ignore:ignoreheading:
** Setup :ignore:ignoreheading:
#+begin_export latex
\lastupdated

\namesection{Rohit}{Goswami}{
 Ph.D., MInstP MRSC MBCS \\
 \href{mailto:rgoswami@ieee.org}{rgoswami@ieee.org}
 \textbullet{} \href{https://rgoswami.me}{rgoswami.me}
 \textbullet{} \href{https://github.com/haozeke}{github.com/haozeke}
 \textbullet{} \href{https://scholar.google.com/citations?hl=en&user=36gIdJMAAAAJ}{Google Scholar}
}
#+end_export

** Work Experience :ignore:ignoreheading:
#+begin_export latex
\section{Work Experience}

\runsubsection{Lab COSMO, EPFL}
\descript{| Systems Specialist (Postdoctoral Researcher)}
\location{2025 -- Present | Lausanne, Switzerland}
\begin{itemize}
\item Developing the \texttt{metatensor} ecosystem for interoperable atomistic machine learning with Prof. Michele Ceriotti and Dr. Guillaume Fraux
\item Integration of machine learning potentials with GROMACS; DLPack support for zero-copy tensor interoperability across C++, Python, Rust, and Fortran
\end{itemize}

\sectionspace

\runsubsection{Queen's University}
\descript{| Visiting Researcher}
\location{2025 | Kingston, Canada}
\begin{itemize}
\item Scaling off-lattice / object kinetic Monte Carlo to over a million atoms for radiation damage modeling with Prof. Laurent B\'{e}land
\end{itemize}

\sectionspace

\runsubsection{University of Iceland}
\descript{| Doctoral Researcher (Rann\'{i}s Doctoral Grant PI)}
\location{2019 -- 2024 | Reykjav\'{i}k, Iceland}
\begin{itemize}
\item Principal investigator: ``Magnetic interactions of itinerant electrons modeled using Bayesian machine learning'' (Rann\'{i}s Research Fund)
\item Developed Gaussian process accelerated saddle point search methods (climbing image NEB, dimer) with adaptive pruning
\item Bayesian hierarchical models for quantitative benchmarking of saddle search algorithms
\end{itemize}

\sectionspace

\runsubsection{Quansight Labs}
\descript{| Software Engineer II}
\location{2021 -- 2025 | Remote (Austin, TX)}
\begin{itemize}
\item Maintained \texttt{f2py} (NumPy's Fortran-to-Python interface) and foundational FOSS scientific codebases
\item Contributed to \texttt{scipy}, \texttt{meson-python}, and \texttt{LFortran} compiler development
\end{itemize}

\sectionspace

\runsubsection{IIT Kanpur}
\descript{| Senior Project Associate / Project Associate}
\location{2018 -- 2020 | Kanpur, India}
\begin{itemize}
\item Computational nanoscience group: ice nucleation analysis (CHILL+), GPU-accelerated MD tools; created \texttt{d-SEAMS}
\item Femtolab: femtosecond laser approaches to quantum information and computation
\end{itemize}

#+end_export

** Education :ignore:ignoreheading:
#+begin_export latex
\section{Education}

\runsubsection{University of Iceland}
\descript{| Ph.D. Physical Sciences}
\location{2019 -- 2025 | Reykjav\'{i}k, Iceland}
Thesis: ``Efficient Exploration of Chemical Kinetics''. Supervised by Prof. Hannes J\'{o}nsson.

\sectionspace

\runsubsection{HBTU Kanpur}
\descript{| B.Tech. Chemical Engineering}
\location{2014 -- 2018 | Kanpur, India}
First Division.

#+end_export

** Publications :ignore:ignoreheading:
#+begin_export latex
\section{Selected Publications}
\nocite{goswamiEfficientImplementationGaussian2025a,bigiMetatensorMetatomicFoundational2025,Goswami2020,stateOfFortran2022,goswamiAdaptivePruningOA2025,sallermannFlowyHighPerformance2025,goswamiBayesianHierarchicalModels2025,goswamiCompositionalAnalysisFragrance2025,goswamiTwodimensionalRMSDProjections2026}
\printbibliography[heading=none, keyword=selected]
#+end_export

** Grants :ignore:ignoreheading:
#+begin_export latex
\section{Grants and Awards}

\runsubsection{COST Action CA23158 Co-Proposer}
\descript{| 575k EUR, 2025--2029}
European Cooperation in Science and Technology network proposal.

\sectionspace

\runsubsection{Rann\'{i}s Doctoral Research Grant}
\descript{| 6650k ISK, 2020--2023}
Icelandic Research Fund grant as PI for Bayesian ML applied to saddle point searches.

\sectionspace

\runsubsection{NumFOCUS Small Development Grant}
\descript{| \$5000 USD, 2020}
For \texttt{d-SEAMS} molecular simulation analysis engine.

\sectionspace

\runsubsection{Springer Best Student Paper Award}
\descript{| Photonics 2016}

#+end_export

** Service :ignore:ignoreheading:
#+begin_export latex
\section{Selected Service}
\begin{itemize}
\item \textbf{JOSS Editor} (2024--present) -- Journal of Open Source Software, topic editor
\item \textbf{NumFOCUS GSoC Admin} (2024--present) -- Coordinating Google Summer of Code across NumFOCUS projects
\item \textbf{IEEE P3173 Vice Chair} (2022--present) -- Standard for Endocrine Disrupting Chemical Hazard Labelling
\item \textbf{Nordic-RSE} -- Board Member; founding Secretary of the Nordic Research Software Engineers association
\item \textbf{IHPC Consultant} (2021--2024) -- Simulation and Data Lab Computational Chemistry, National HPC center of Iceland
\item \textbf{Reviewer}: Nature Comms, PRL, PRA, PRE, JOSS (80+), PLOS ONE, IOP journals, PeerJ
\end{itemize}
#+end_export

** Talks :ignore:ignoreheading:
#+begin_export latex
\section{Selected Presentations}
\begin{itemize}
\item \textbf{ACS Fall 2025} -- ``Managing concurrency for high throughput adaptive kinetic Monte Carlo'' (Washington, DC)
\item \textbf{Psi-k 2025} -- ``Advocating for standardized APIs for common procedures'' (Liverpool, UK)
\item \textbf{Kernel aKMC 2025} -- ``Towards a million atoms and a thousand KMC steps a day'' (Queen's, Canada)
\item \textbf{APS Global Physics Summit 2025} -- ``Contending with concurrency across programming languages'' (Anaheim, CA)
\item \textbf{CECAM-LTS-MAP 2024} -- ``Accelerating Saddle Searches with Gaussian Process Regression'' (Invited, Lausanne)
\item \textbf{IPAM TMRC2 2023} -- ``Computational Chemistry and Possible Tensor Applications'' (Invited, UCLA)
\item \textbf{14th Icelandic HPC Workshop 2024} -- ``Scaling workflows from development to HPC''
\end{itemize}
#+end_export

** Software :ignore:ignoreheading:
#+begin_export latex
\section{Open Source Software}
\begin{itemize}
\item \textbf{d-SEAMS} (co-creator) -- Molecular dynamics trajectory analysis engine (JCIM 2020, NumFOCUS SDG funded)
\item \textbf{f2py / NumPy} (maintainer) -- Fortran-to-Python interface generator; core NumPy component
\item \textbf{fastMatMR} -- rOpenSci reviewed R bindings for fast Matrix Market I/O
\item \textbf{wailord} -- Python library for ORCA quantum chemistry workflows (SciPy 2022)
\item \textbf{flowy} -- High performance probabilistic lava emplacement prediction (CPC 2025)
\item \textbf{eOn} (maintainer) -- Long timescale dynamics code with Gaussian Process accelerated saddle searches
\item \textbf{metatensor} (maintainer) -- Atomistic machine learning toolkit (JCP 2026)
\end{itemize}
#+end_export

** Skills :ignore:ignoreheading:
#+begin_export latex
\section{Technical Skills}

\skillsection{HPC}{LAMMPS, GROMACS, MPI, CUDA, Nix, Spack, EasyBuild, Slurm, containers (Docker/Singularity)}
\skillsection{Languages}{C++, Python, Fortran, Rust, R, Julia, Shell}
\skillsection{Tools}{CMake, Meson, Git, CI/CD (GitHub Actions, Azure), \LaTeX, Emacs}
\skillsection{ML/Data}{PyTorch, scikit-learn, GPy, Stan, Bayesian optimization, Gaussian processes}
#+end_export

** Memberships :ignore:ignoreheading:
#+begin_export latex
\section{Professional Memberships}
IOP (MInstP) \textbullet{} RSC (MRSC) \textbullet{} BCS (MBCS) \textbullet{} ACM \textbullet{} APS \textbullet{} IEEE \textbullet{} AIChE
#+end_export

** End Document :ignore:ignoreheading:noexport:
Org handles \end{document} automatically.

* Notes :noexport:ignoreheading:ignore:
** TODO Verify page count is exactly 2
** TODO Tune publication selection for SURF relevance
